services:
  challenge:
    build: challenge
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: Matt
      DB_PASSWORD: '#Matt1001'
      DB_URL: jdbc:mysql://mattdb.cna2i0yiwjyg.us-east-2.rds.amazonaws.com:3306/mattdb?serverTimeZone=UTC
      SECRET_KEY: XTHISXISXTHEXLONGXXKEYXFORXTHISXCHALLENGEX1001XMATTX
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mjdbc:mysql://mattdb.cna2i0yiwjyg.us-east-2.rds.amazonaws.com:3306/mattdb'
      - 'MYSQL_PASSWORD=#Matt1001'
      - 'MYSQL_USER=Matt'
    ports:
      - '3306'
